# Location of the website relative to the domain name, used for absolute links.
# Omit this if hosting directly on the domain.
baseurl: /nethack-www

# URL back to the web server, used by RSS feeds to link back to the website.
#url: http://www.nethack.org
url: https://tung.github.io

# Generate the site from a fixed timezone.
timezone: UTC

exclude: [Gemfile, Gemfile.lock]

kramdown:
  input: GFM # GitHub Flavored Markdown
  smart_quotes: apos,apos,quot,quot # Disable smart quotes.

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "blog"
    values:
      is_blog_page: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "blog"
      layout: "blog-post"
      is_blog_page: true
      is_blog_post: true
