title: NetHack
description: >
  The classic roguelike adventure: Descend the Mazes of Menace and retrieve the
  Amulet of Yendor!

# Location of the website relative to the domain name, used for absolute links.
# Omit this if hosting directly on the domain.
baseurl: /nethack-www

# URL back to the web server, used by RSS feeds to link back to the website.
#url: http://www.nethack.org
url: https://tung.github.io

# Fill these URLs in when their respective systems go live.
repo:
  site_url: "#TODO" # e.g. https://github.com/nethack-devteam/nethack
  clone_url: https://github.com/nethack-devteam/nethack.git
public_bug_tracker_url: "#TODO" # e.g. https://github.com/nethack-devteam/nethack/issues
forums_url: "#TODO" # e.g. https://forums.nethack.org

# Generate the site from a fixed timezone.
timezone: UTC

# Pagination.
paginate: 10
paginate_path: "/blog/page:num"

exclude: [Gemfile, Gemfile.lock, README.md]

gems:
  - jekyll-redirect-from

collections:
  screenshots:
  authors:
    output: true
    permalink: "/blog/authors/:path.html"
  tags:
    output: true
    permalink: "/blog/tags/:path.html"

kramdown:
  input: GFM # GitHub Flavored Markdown
  smart_quotes: apos,apos,quot,quot # Disable smart quotes.

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "blog"
    values:
      is_blog_page: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "blog"
      layout: "blog-post"
      is_blog_page: true
      is_blog_post: true
  -
    scope:
      path: "blog/authors"
    values:
      layout: "author"
  -
    scope:
      path: "blog/tags"
    values:
      layout: "tag"
